### ISSUE TITLE
Login With Amazon Connector

### ISSUE THREAD

**Issue by AlexzSouz** [hengsoheak/DotNetCore2Security#1]
Hello everyone,

Are you guys working on a security layer for "Login with Amazon" using OAuth2? I've been working in a project using IdentityServer4 and I had to integrate it with Amazon authentication and this was a bit exhausting.

**Comment by higtrollers** [comment]
I've create a extension for Login with Amazon following the same code standards you guys have there, I also tested with against the "sample app" you have and it's working as expected. I would like to contribute with this code!

**Comment by AlexzSouz** [comment]
Will reformulate it based on your issues template
